# Generated by Django 4.0.6 on 2022-07-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkiapp', '0002_paymentinstallment_remaining_amountt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinstallment',
            name='remaining_amountt',
        ),
    ]
